### ISSUE TITLE
Novel API 구현 

### ISSUE THREAD

**Issue by yooyouny** [yooyouny/webnovel-api-server#2]
### 📄 Describe

1. Creator가 신규 노벨을 등록한다.
2. Creator가 노벨 정보를 수정한다.
3. Creator가 등록된 노벨을 삭제한다.

### ✅ Tasks

- [ ] API & DB Table & Entity 설계
- [ ] 노벨 등록 API 구현
- [ ] 노벨 수정 API 구현
- [ ] 노벨 삭제 API 구현
